### ISSUE TITLE
Allow server list sorting

### ISSUE THREAD

**Issue by sxiii** [jamulussoftware/jamulus#1143]
Asc/desc sort function into server list by number of users / location / ping / server name

I would like to choose server based on different criteria.

**Comment by ann0see** [comment]
Maybe this is already possible with the filter option next to the list selection?

**Comment by dcorson-ticino-com** [comment]
For the moment the server list is only sorted by ping time.
The filter function reduces the list to servers where the filter string is found in one of the fields.
Personally I have never felt the need to sort by anything other than by ping, the filter works well for special occasions, but it would certainly be possible if we decide that is desirable.

**Comment by gilgongo** [comment]
Congratulations @sxiii ! You are the first person to use our new Issue reporting template. 

Since this is I think a pretty clear request (and sorting is in fact implemented when --showallservers is on I think), I propose we keep it here. If anyone wants to pull it into a protracted discussion (eg if this feature would break something) they can do, at which point we can move it out to Discussions if needed.

**Comment by dcorson-ticino-com** [comment]
I correct myself.  
Because of a apparent code error, the code doesn't do what the commentary says, you can sort on all but the server name when you use the  --showallservers command line option.
The disadvantage is that you see all the servers the central server knows about, even those that do not respond to the pings of your computer.
A registration number is also prepended to the server name which is why the sort on server name does not work.

**Comment by gilgongo** [comment]
OK so this isn't as straightforward as making sorting available in the non-showallservers condition then. And there may be other thing. Moving to a discussion.
