### ISSUE TITLE
Add rudimentary compressor and LPF/HPF

### ISSUE THREAD

**Issue by reneknuvers** [jamulussoftware/jamulus#1286]
I would like to see a rudimentary compressor function, to eliminate issues by inexperienced users with their gains turned up too high. Opus doesn’t seem to handle clipping signals all that well. A very basic ‘AGC’ algorithm could help.

As an alternative a long stretch RMS calculator could drive on screen hints ‘you are loud, turn down the gain on channel 1/L’.

the most rudimentary solution would be a clipping indicator. 

To give the opus encoder a good time while creating a better sound experience at the same time, a selectable -6dB/oct low pass and high pass filter (or maybe a bit steeper) at a  fixed frequency (150Hz and 10kHz) would be nice. It would kill microphone rumble and eliminate hard to encode high pitched noise. Filtering could take place on the clients side as there is probably the most available computing power, plus this would not harm any other musician on the server.
By nature the filtering would add a bit of latency. The choice of FIR or IIR filters determines sound quality, processor load and added latency.

Above the input VU, switches with a control light would activate the compressor, LPF and HPF.
When a mic or similar instrument is selected in the profile, a suggestion is made to engage both LPF and HPF. Other instruments may suggest this too,  either one of the two. Decision is hard coded and should be based on experience and instrument’s harmonic content.

Compressor is engaged by default and can be turned off by the user. VU is augmented with a Gain Reduction meter running top-down. 
 
All settings are retained in the local client configuration.

**Comment by ann0see** [comment]
Hi thank you for opening this issue.

> I would like to see a rudimentary compressor function, to eliminate issues by inexperienced users with their gains turned up too high. 

Not sure if a compressor is the right thing here (especially if it adds complexity in the Jamulus source code and modifies audio signal)? It doesn't fix the core issue with high input gain:

I think it should be possible to tell them how to turn down their gain in Windows/macOS, since it's probably only a one time action. Also, they could move away from their mic?

The next version will have basic feedback/clipping detection: https://github.com/jamulussoftware/jamulus/pull/1179


> the most rudimentary solution would be a clipping indicator.

Not sure, but don't we have this already (at least in fancy mode)?


So you'd suggest adding
1. A compressor
2. High-pass and Low-Pass filters?

**Comment by dcorson-ticino-com** [comment]
>Not sure, but don't we have this already (at least in fancy mode)?

There is a clipping indication in all 3 skins.
I do not think that we should be doing anything that reduces the audio quality like compression.
It is a one time setting to set your input volume correctly.
Once you know how it is just a couple of seconds to check after connecting with mute myself set.

For my ears there is often already distortion before clipping sets in.
That depends on the audio hardware of computer or interface.
I tell people to set their input volume so that loudest playing/singing just doesn't set the first red led on the fancy skin.
That may be a little conservative, but I hate distortion.
Note that the "normal" skins do not change colors except for clipping so it may be more difficult to describe the best volume indication.

**Comment by gilgongo** [comment]
Hi @reneknuvers thanks for this suggestion. Until we get an actionable spec for any work on this I'll move it to discussion if that's OK.
