### ISSUE TITLE
Optimize UI for touch screen control

### ISSUE THREAD

**Issue by reneknuvers** [jamulussoftware/jamulus#1287]
Users run clients on touch-enabled devices, or control raspberry pi-like clients through VNC or teamviewer on a tablet. Yet current UI has tiny features and is hard to control.

increased spacing, larger responsive surface areas would better enable touch control.

following touch interface guidelines should enable further improvements.

**Comment by ann0see** [comment]
Hi! Thank you for opening an issue. 

I understand that better touch screen support would be great. In general I'd say that this should at least be discussed in the UI thread: https://github.com/jamulussoftware/jamulus/discussions/1150

I'd suggest you to participate there. In the meantime, I'll close this issue since I doubt we can do it right away.
