### ISSUE TITLE
Don't dismiss Connection Setup dialog after connect

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulus#1368]
In 3.7.0, opening the Connection Setup dialog and then connecting to a server causes the Connection Setup dialog to be dismissed.  There are situations where it would be great if the Connection Setup dialog could remain open, making it easier to then switch to another server.  This would be particularly beneficial for the volunteers and performers on the WorldJam.

Don't change the default behavior (dismiss the Connection Setup dialog), but allow it to be changed via a (new) checkbox in the Connection Setup dialog OR a new menu item on the Edit menu.  Perhaps not necessary to save the setting between sessions.

**Comment by gilgongo** [comment]
I believe the reason it closes is to minimise the considerable traffic that it generates which could impact the stability of a jam session. It has been suggested (on the UI thread I think) that to allow people to leave it open it should only poll once or twice when opened, and then have a "refresh" button for this reason.

Either way, so that we can have agreed work tickets on the issues list, I'll move this to discussion prior to a spec for any resulting PR.
