### ISSUE TITLE
Setup a card sorting survey for menu categories

### ISSUE THREAD

**Issue by djfun** [jamulussoftware/jamulus#1410]
For the discussion see #1026
Setup a card sorting with uxtweak, trello, .. to find the best menu categories for all menu items.
Maybe also add some functions which are currently not represented by a menu item.

**Comment by djfun** [comment]
I started something here: https://study.kardsort.com/jamlus-menu-items
@pljones, @gilgongo, @mulyaj, @chrisrimple, @nefarius2001, @hoffie : am I missing any items?

**Comment by mulyaj** [comment]
Looks good! I think that might be enough if we're just trying to solve the current menu categorization.

I'm wondering if there needs to be more explanation, or maybe even screenshots for the cards. We'll probably need that if we're going to send this to random users.

**Comment by gilgongo** [comment]
> I'm wondering if there needs to be more explanation

These tools always seem a bit thin on that stuff. Might be worth maybe creating a "landing page" with screen shot, explanation etc. and then a link to the card sort from there? If you want I can add research.jamulus.io for that if you have somewhere to point it?

**Comment by mulyaj** [comment]
We should hopefully employ some participant screening to get a decent spread of users. 

I'm sure it'll be easy to get current Jamulus users to do the study, but I'm wondering where we'll get random users. 

@gilgongo The landing page sounds good, but I'm a bit worried about retention there - it's hard getting someone to complete a study in the first place, not sure if someone would want to read a brief before completing one. In that case, @djfun is it possible to add images onto the introduction or on the cards, and is there a limit to characters within a card?

**Comment by djfun** [comment]
There is a character limit of 200 for the card info. The intro text can be formatted, but it doesn't seem that I can add images there, only links to images.
So if you want screenshots, we need to create a separate page for that.

**Comment by gilgongo** [comment]
I guess you are saying "in particular the menu bar on top" on the intro page, so maybe that's enough as we can assume they know what Jamulus is of course :-)

Maybe on the next page you could just add a bit of "orientation" so that:

_On the next page you will see a list of menu items._

_Thinking about using Jamulus, please create categories where you would expect to find those items. If you think one of the items should not be a menu item, please choose where they should be found ("Settings dialog", "Main window", ..)._

(Hm - does this text have to be the same as "instuctions" on the next page? That would mean the first line is confusing there...)

BTW there seems to be a category already there called "Help". Is that intentional?

**Comment by djfun** [comment]
It is currently in "Hybrid" mode, where you can specify some categories, but still allow the user to add new ones. "Help" was the only stable category when I set this up, but now that I think about it, this might not even be the case.. Should I switch it to "Open" mode?
Yes, the instructions text seems to be shown both before the actual sorting and when clicking "view instructions".

**Comment by gilgongo** [comment]
Oh I'd just put it into open mode. We can do a closed one later to see how that compares to what we get this time around (interpreting open sorts is a bit harder though).

**Comment by djfun** [comment]
I changed it to open mode and fixed the typo in the url: https://study.kardsort.com/jamulus-menu-items

**Comment by gilgongo** [comment]
OK that's better I think. On the opening instructions, I know from experience that people can be confused by the term "sort" if they think it's about priority ordering and not grouping. Also, it helps to echo the words used in the UI they see on the sorting page (eg "create category"). So I'd amend the instructions to be:

_"Thinking about when you use Jamulus, please create categories where you would expect to find items on Jamulus's menu. If you think any items should not be a menu item, please create a group where they should be found ("Settings dialog", "Main window", ..)."_

BTW the "thinking about..." prefix is a standard technique for getting people into the right mental "zone" so that they provide comparable answers. We don't want people thinking we want them sorted according to whether they rhyme or something :-)

**Comment by ann0see** [comment]
Is there any outcome of this issue?

**Comment by mulyaj** [comment]
Update everyone, I've made an [updated version](https://study.kardsort.com/jamulus-card-sort) of the card sort, and I've just posted it on the facebook group.

**Comment by gilgongo** [comment]
Are you now getting results? I was going to ask about some of the cards and how we'd interpret the results for those, but no matter if it's gone live now.

**Comment by ann0see** [comment]
@mulyaj your survey gives an error if I want to access it. Is it disabled?

**Comment by mulyaj** [comment]
@ann0see Made some edits to it, it should be back up now.

**Comment by pljones** [comment]
Do @jp8's menu changes mean this can be closed?

**Comment by djfun** [comment]
yes, I think this can be closed.
