### ISSUE TITLE
Loud Noise on the Headphones at Irregular Intervals

### ISSUE THREAD

**Issue by StuMuPlayer** [jamulussoftware/jamulus#1467]
Hardware: Mac mini (Late 2012) Core i5
macOS 10.14.6  and Jamulus 3.7.0
Audio In: Zoom U-44 with 2 Mics or Zoom H2n
Audio Out: Headphone (beyerdynamic DT-770 pro) on internal Audio Out

In this constellation, I always get a loud noise on the headphones at irregular intervals (other participants in the session do not hear this noise); this noise does not occur when I also set the audio interface as an output and pick up the sound there with the (same) headphone.
The noise is reproducible, but only when music is transmitted, not in silence, and not only on the Mac Mini but also on a MacBook Pro (2017) with macOS 11.2.3 and also Jamulus 3.7.0.

Best Regards

**Comment by chrisrimple** [comment]
Interesting.  I've been having a similar problem, but was attributing it to CPU load and other factors unrelated to the Jamulus client.

I have a Mid 2015 MacBook Pro, MacOS 10.14.6 Mojave, Jamulus 3.7.0, and iConnectivity AUDIO4+ audio interface (AI).  I run it in two configurations:

Yes MainStage
Keys/Mic > AI > MainStage > BlackHole > Jamulus IN
Jamulus OUT > AI > Headphones

No MainStage
Keys/Mic > AI > Jamulus IN
Jamulus OUT > AI > Headphones

The "Yes MainStage" configuration is a recent change for me, that I've been testing for a few weeks.  On BOTH 3.6.x and now 3.7.0, I'm experiencing irregular static in the sound, and it's much, much more frequent in the "Yes MainStage" configuration than the "No MainStage" configuration.

I'm connected to a 3.7.0 server running on Debian 10, but I suspect that this is a Jamulus client problem because other musicians are not hearing the static at the same time.

**Comment by StuMuPlayer** [comment]
I'm pretty sure it's a Jamulus client thing. I don't have any problems listening to music with the same output and headphones with any other programme.
I tried to test different audio output settings using the "Audio MIDI Setup" program provided by the operating system, but Jamulus always overwrites all my settings with 2ch, 20-bit and 48 KHz.

**Comment by gene96817** [comment]
I am having a similar problem with same pattern. The difference is my sound drops out for 1-2 seconds. None of the other participants seem to hear a problem.

MacBook Pro (2016), MacOS 11.2.3, Blue Snowball, headphones on internal audio jack, Jamulus 3.6.2 or 3.7.0.
Server 3.6.2 or 3.7.0 on same local network.

**Comment by dcorson-ticino-com** [comment]
>I don't have any problems listening to music with the same output and headphones with any other programme.

Listening to music has next to nothing to do with what Jamulus does, even if you are streaming music you are working with huge buffers and big latency (which you don't hear as you can't react in real time).  Jamulus is a real time, low latency, highly reactive program that depends on the ability of both the audio drivers and the Internet connection to keep up in real time.

Is it possible that there is some background process on the computer running at intervals causing this?

It is indeed strange that all of these occurrences are on MACs which may call into question the MAC drivers, but I think the chances are high that they will all be linked to Internet connection problems in the end (if it is not caused by background processes).

Note that Jamulus requires 2 channels with 48k sampling for use so it is not strange that it sets the settings as such.

**Comment by ann0see** [comment]
Maybe there are clock/synchronisation issues since you're using two devices.

**Comment by StuMuPlayer** [comment]
that's my guess too, but I haven't found a way to test other clock/sync settings yet, because the client overwrites the changed settings every time it starts.

**Comment by dcorson-ticino-com** [comment]
>that's my guess too, but I haven't found a way to test other clock/sync settings yet, because the client overwrites the changed settings every time it starts.

As I said above, Jamulus requires 2 channels with 48k sampling so there is no need to try other clock rates.

**Comment by gilgongo** [comment]
@StuMuPlayer Are you still being affected by this? I don't think we've had any further reports of it.
