### ISSUE TITLE
Jamulus -? is not translated. English only

### ISSUE THREAD

**Issue by DavidSavinkoff** [jamulussoftware/jamulus#1653]
**Describe the bug**

Jamulus -? is not translated.
**To Reproduce**

Jamulus -?
**Expected behavior**

Command line help should be in selected language
**Screenshots**

**Operating system**
 All OS

**Version of Jamulus**
 All versions

**Additional context**

**Comment by softins** [comment]
The language selected in the GUI is only for the GUI itself, and is stored in the ini file. At the point where `Jamulus -?` or `Jamulus --help` is executed, the ini file has not been read, and may not even exist.

The only logical item to consult for this would be the environment variable `LANG`. But as a point of comparison, on the Linux systems I use, the command `nano --help` gives the help text in English only, even when I have set `LANG` to other values, such as `fr`, `fr.UTF-8`, `de` or `de.UTF-8`, and `/usr/share/locale/*/LC_MESSAGES/nano.mo` does exist for those languages. Similarly for other commands.

So I don't think Jamulus behaves any worse in this regard.

**Comment by DavidSavinkoff** [comment]
> So I don't think Jamulus behaves any worse in this regard.

If its not a bug, then its not a bug. Maybe close this after a few comments, or days, if that is the right thing to do.

**Comment by hoffie** [comment]
I agree, it's not a bug, because nobody has ever tried to make this work.
Lots of standard Linux tools do have localized `--help` texts (`cat`, `ls`, `grep` and, for me, even `nano` did have it), so I think this is a reasonable request.

It would mean some work for `--help` though and it may trigger the subsequent question if other command line messages would have to be translated as well.

If there's little demand, I'd keep it as-is. If this was helpful for lots of people, we should probably do it.

As you suggest, maybe keep this issue open for some days. It will still be searchable afterwards, so anybody coming across this issue can still voice their opinion later.
