### ISSUE TITLE
[android]  chat dialog cannot be closed

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1763]
**Describe the bug**
When the chat window opens on Android, it uses the fullscreen and does not allow to return (close) the window to get back to the main dialog.

**To Reproduce**
Open the app on Android and open the Chat window
When using a server that has "license" enabled, you automatically get the chat window displayed and cannot even the app at all.

**Expected behavior**
A close option should be available to the Chat window on Android device (perhaps on iOS as well).
The default x (available in other platforms) does not show on Android.

**Operating system**
Android 10

**Version of Jamulus**
3.8.0rc1

**Comment by ann0see** [comment]
I think https://github.com/jamulussoftware/jamulus/pull/1512 will fix this

**Comment by ngocdh** [comment]
Yes indeed, see https://github.com/jamulussoftware/jamulus/pull/1512/files#diff-0eda22ffb00bf0bbb2947f9e26d668a276a8934b68f231700d231676181ee5e8

**Comment by henkdegroot** [comment]
Wow...that is a very quick solution! Works correct indeed....I had seen the PR a while ago...and thought it was merged already.
Guess I was mistaken and should have checked first.

**Comment by dcorson-ticino-com** [comment]
I think the solution is a one window interface, if we decide to use it.
Here is a first stab at something useful: 
https://github.com/jamulussoftware/jamulus/discussions/1343#discussion-3290638

**Comment by ngocdh** [comment]
> one window interface

@dcorson-ticino-com I love it actually. But I have to disagree here, because of mobile devices' small screens. 
For desktop, I vote for one window interface.

**Comment by ann0see** [comment]
Yep. That's what Jamulus might look like in future ;-). However I suggested small steps to not confuse users.

**Comment by henkdegroot** [comment]
![mobile-preview](https://user-images.githubusercontent.com/13550012/119722883-1e0fd980-be6d-11eb-8a37-8f9c48203ae4.jpg)

It is not that bad at all on my mobile (screen resolution of 720 x 1480).....a few tweaks here and there...and we are back into the future :)

**Comment by dcorson-ticino-com** [comment]
> But I have to disagree here, because of mobile devices' small screens.

Then I am totally confused.  If the screen is too small, use a device with a screen size that is OK.
Why do you want to use it at all?  
I can't imagine how this should work if every time a chat comes the screen changes, one would spend more time playing with ones device than playing ones instrument.
The other guy who posted today about his Android had a screen resolution that is higher than on my PC.  With that even the normal Jamulus interface should work just as well as on a PC.
Apparently these devices don't let you use that resolution. :(

**Comment by ngocdh** [comment]
> It is not that bad at all on my mobile (screen resolution of 720 x 1480).....a few tweaks here and there...and we are back into the future :)

I'd love for those tweaks to happen. Because as it is now, if you're in a room with 10, you'll have to deal with small scrollbars which are hard to use (touch screen gestures not supported now). And those settings tabs, also hard to click on.

So if there's a way for everything to fit nicely and not so hard to manœuvre, I'm in.

**Comment by ngocdh** [comment]
> Why do you want to use it at all?  

Because it's practical.


> one would spend more time playing with ones device than playing ones instrument.

Which is why mobile apps must have their own design so that it's easy for users to use. Take chat window example: for mobile devices we could use notifications instead of the whole window.

Some mobile devices might have high resolution, but that also means controls are small on a (relatively) small screen, which makes them hard to use. At least that's what I get from using current Jamulus on mobile devices. 

But I'm sure we can make it better :)
