### ISSUE TITLE
Move tools/ scripts to own repo

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1764]
As discussed in https://github.com/jamulussoftware/jamulus/pull/1594#discussion_r634813064, we should consider moving some non-core scripts and documentation into its own repo.

- [ ] Agree on a repo name (tools, utils, automation, maintain, administration, management?) (Updated with suggestions by @ann0see)
- [ ] Should TRANSLATING.md (and possibly other documents) be moved?
- [ ] Move stuff

I'd suggest:
Repo name: (I'm not really happy with any of the suggested terms yet)
What to move:
- Scripts within the root of tools/* (not: git submodules)
- I think we should mainly move maintainer-only stuff and keep documentation which is intended for others to read in the main repo?

**Comment by ann0see** [comment]
What about administration, management for the name?

I'd vote for maintain.

**Comment by softins** [comment]
Do you really mean to a separate repo? Or just to a separate folder within the jamulus repo?

I wouldn't want people to have to checkout two different repos just to get everything. Files like CONTRIBUTING.md and TRANSLATING.md are intended to be conspicuous to potential contributors. If they were in a separate repo, they wouldn't be.

**Comment by hoffie** [comment]
> Do you really mean to a separate repo? Or just to a separate folder within the jamulus repo?

I really meant a separate repo for the scripts which we (main developers) use for release preparation.

I think documentation should be kept within the jamulus repo, right.

(I'd also be ok with keeping everything as-is; it's just that these scripts don't have to be part of the source tarball and don't have to go through the usual two-person review -- probably one-person review, still)

**Comment by ann0see** [comment]
We just discussed about also moving some stuff related to design (and language) to a separate repo.

**Comment by ann0see** [comment]
@jamulussoftware/maindevelopers @jamulussoftware/designers can we agree on this one?

I think we should create a repo (name: maintain) and add:

1. all the scripts/md files related to the release process there
2. Move the style and tone guide, and https://github.com/jamulussoftware/jamuluswebsite/pull/408 there

**Comment by pljones** [comment]
> I'd vote for maintain.

That's a verb.  A repository is a place you put things and a place wants to be a noun, really.

"administration" would cover process documentation and tools used to apply those processes.

What should not be in it?  Well, we want things in the specific repos that are about those repos and useful to anyone outside the core team - so the automation for building Jamulus should stay in jamulussoftware/jamulus, as would `CONTRIBUTING.md`, as examples.  Anything someone contributing to _that_ repo should be aware of should stay there, on the whole.

I also think some "common processes" should move to the Wiki, rather than the admin repo.  These would be "public" processes common to website and code repos, for example.  (Translations is what I'm thinking of.)

What should be in it?  "Clutter" that has nothing to do with building Jamulus or maintaining the website itself.  That's pretty much the release process but I can't think of anything else.

Then there's "what's on the website itself that should move to a new site?", which would cover things like jamulussoftware/jamuluswebsite#408.

**Comment by ann0see** [comment]
> "administration" would cover process documentation and tools used to apply those processes.

Ok. Agreed. 

> I also think some "common processes" should move to the Wiki, rather than the admin repo. 

Which could also include the release process except for the issue template and the scripts in the site.

In theory we could just paste the issue template on the website (as code block) and paste it into an issue once we start a release.

So only the scripts for the release would go to the new repo while TRANSLATING.md and RELEASE-PROCESS.md would be moved to the website?

**Comment by gilgongo** [comment]
What's the status of this issue? Did we decide against a separate repo and instead have a directory in the main one? Can we close this?

**Comment by pljones** [comment]
> So only the scripts for the release would go to the new repo while TRANSLATING.md and RELEASE-PROCESS.md would be moved to the website?

That argues for "release-process" as a repo name...  or maybe "maintainer-processes" to allow for future expansion.

Just to be clear:
* anything someone forking jamulussoftware/jamulus or jamulussoftware/jamuluswebsite needs in order to do development (that we provide) - e.g. build scripts for platforms - should remain, to make people's lives easy.
* anything that's only used by maintainers to manage jamulussoftware/* would move out.

What that means in practice would need looking into.

**Comment by gilgongo** [comment]
OK so if we take that logic, we're looking at making a separate repo ('maintainer-processes'?) and moving some stuff that we have in the main repo (or repos?) into that. 

I always feel a bit nervous about "fragmenting" systems like this in case it seeds endless debates about what should go where (and the more fragments the more debates). But if we feel there is a logical or natural "cleavage" here between things then I hope that will be OK...

**Comment by hoffie** [comment]
Some new aspect to consider: The scripts we move out of the jamulus repo will be harder to work with in from within Github actions, especially if they work on the jamulus repo itself. At least those should probably be kept.

As the small number (even if growing a bit) of scripts is currently not an issue at all, this is rather cosmetic, so maybe we should just live with it for now?

**Comment by ann0see** [comment]
Agree. Maybe the name tools for the folder is not clear enough. Would maintenance be better? And the other documentation files could be moved into a docs/ folder?

**Comment by ann0see** [comment]
Since you're working on automating the scripts, I think it doen't make sense to delete or move them anymore. Let's close this issue.
