### ISSUE TITLE
Mute Myself sometimes leads to maximum level of My channel

### ISSUE THREAD

**Issue by jregener62** [jamulussoftware/jamulus#1935]
**Describe the bug**
'Mute Myself' sometimes leads to maximum level of My channel. In these situations it is not possible to change the level of My channel. It stays on maximum.

**To Reproduce**
1. set 'My channel' to any level below maximum
2. enable 'Mute Myself'

**Expected behavior**
'My channel' should not change level.

**Operating system**
macOS Big Sur 11.4, iMac Late 2015, Apogee Element 46

**Version of Jamulus**
3.8.0

**Comment by ann0see** [comment]
I think this bug was already fixed: #1838 so hopefully it’ll be part of the next version

**Comment by ann0see** [comment]
Tagged a nightly release for you: https://github.com/jamulussoftware/jamulus/releases/tag/r3.8.0devNightly1

Once it's built, scroll down to assets, download and install the build and test the bug is fixed.

**Comment by jregener62** [comment]
Thanks. Don't see the issue anymore so far. I will verify the fix for some time and let you know the test results then.

**Comment by ann0see** [comment]
Great! I‘ll close it then. If you experience it again, just re-open it and give a comment

**Comment by jregener62** [comment]
Unfortunately I see the issue again. In this case I was the only participant on a server with 'Mute Myself' enabled. The volume of my channel raised to maximum when another participant joined the server. Workaround is to re-join the server.

**Comment by ann0see** [comment]
Ok. Strange. Could you please update the above bug description? 

So your bug is reproducible? Did you check the linked Pull request and verify that the other bug is not occurring? If that’s the case, we need to re-open the other issue.

**Comment by jregener62** [comment]
Unfortunately not reproducible every time but only sometimes. I'll try to create a configuration where the issue is always reproducible.

**Comment by jregener62** [comment]
I've found a reproducible situation, at least during one Jamulus' runtime. The issue only happens on several servers. Unfortunately I don't see a regularity here but I hope it is a hint to a possible cause of the bug. Please see attached screen movie (with sound).

**Comment by ann0see** [comment]
- Just edited your post to make the link clickable -


Yes, this looks like a bug. @npostavs knows a bit more about the (old) bug, so tagging it here. 

I don’t think it‘s server related since mute myself is a client feature?

**Comment by jregener62** [comment]
I definitely have different results on several servers, although this feature and this bug is not likely to be related to server functionality. As a next test I would like to backup and then reset all settings but I cannot find a pref file on Mac. Any hints?

**Comment by ann0see** [comment]
Not sure where macOS usually saves preferences, but the file could be somewhere under ~/Library/???/Jamulus.ini

**Comment by npostavs** [comment]
>  @npostavs knows a bit more about the (old) bug, so tagging it here.

Not sure which old bug you refer to.

**Comment by ann0see** [comment]
#909

**Comment by ann0see** [comment]
To me it seems as if both bugs might be related.

@jregener62 can we clarify if #909 is in fact a different bug (since it seems to be unrelated to servers) or are they the same?

**Comment by jregener62** [comment]
I guess that #909 and this bug are the same. In both cases edits on the own channel of the mixer is taking no effect. This is not always reproducible. Until now I have not found reliable steps to reproduce. All I can say is that if it happens it happens on some servers but not on other servers during runtime.  I will continue to try to find save steps to reproduce.

**Comment by softins** [comment]
> All I can say is that if it happens it happens on some servers but not on other servers during runtime.

@jregener62, when you find you are on a server where it happens, please visit [Jamulus Explorer](https://explorer.jamulus.io) and determine the Jamulus version of the server in question. There are a lot of older servers out there, and it would help a lot to know whether the issue is only with older servers, or also with some current ones.

**Comment by jregener62** [comment]
I've tested different servers now but there is still no regularity. I saw the issue on servers running 3.5x up to 3.8...dev. Sometimes it happens when I join a server, sometimes it happens later when a new participant joins the server.

**Comment by softins** [comment]
> I've found a reproducible situation, at least during one Jamulus' runtime. The issue only happens on several servers. Unfortunately I don't see a regularity here but I hope it is a hint to a possible cause of the bug. Please see attached screen movie (with sound). https://www.dropbox.com/s/ght18vlqnn8tb6p/Mute%20Myself%20Bug%20small.mov?dl=0

The video was very useful. It showed me the following things:

1. The issue is to do with the _sound level_, not the behaviour of the fader. So it was not able to be observed just by watching the screen. It was necessary to test by feeding a tone into the client. This was not clear to me from the original description, and I was initially expecting to see the fader move unexpectedly.
2. When connected to **Directory Server**, the expected behaviour was observed. That server is running 3.8.0. The channel mute and fader level caused the expected changes to the sound heard.
3. When connected to **Bierimpuls**, the mute and fader controls were not effective. The Bierimpuls server is running a very old version, `3.5.5git`, which is a development version _prior to_ the 3.5.5 release.
4. When connected to **Moustache's Club**, the mute and fader controls worked again. That server is not up currently, so I can't check its version.
5. When connected back to **Bierimpuls** the controls were again ineffective, but this time the tone was not heard. This will be because of the state left when disconnecting from the previous server.
6. Returning to **Directory Server**, operation was as expected again.

The problem here is the very old version running on Bierimpuls. Please see https://github.com/jamulussoftware/jamulus/issues/148#issuecomment-634208150 particularly, and then that whole issue (which was raised by me).

In summary, the client does not know which is _its own_ fader unless informed by the server using a `CLIENT_ID` message. Without this knowledge, it cannot control the level of its own signal being mixed locally in "mute myself" mode. The Bierimpuls server is too old to send the `CLIENT_ID` message, and consequently, when connected to it, the client has no idea which fader should control the local signal in the local mix. The first server version to send `CLIENT_ID` is the **3.5.5** release from 26 May 2020.

@jregener62, do you know the Bierimpuls people? If so, please encourage them to update their very old server!

For this bug to be considered still open, we need to observe it using:
* the Nightly1 build linked to above, AND
* a server running a recent version. At least 3.5.5, but preferably 3.7.0 or 3.8.0.

**Comment by jregener62** [comment]
Thanks for the details.

I now will check https://explorer.jamulus.io for next days or so and close the bug if I don’t see it anymore with servers > 3.5.

**Comment by jregener62** [comment]
I checked again last few days by only connecting to servers ver. >3.5 and I haven't seen the issue anymore. Closing

**Comment by jregener62** [comment]
I checked again last few days by only connecting to servers ver. >3.5 and I haven't seen the issue anymore. Closing and thanks for your support finding out.
