### ISSUE TITLE
Jamulus MacOS Legacy installer does not work on Yosemite 10.10.5

### ISSUE THREAD

**Issue by georg-sch** [jamulussoftware/jamulus#2143]
**Describe the bug**

Tried to download and install the "[jamulus_3.8.1_mac_legacy.dmg](https://github.com/jamulussoftware/jamulus/releases/download/r3_8_1/jamulus_3.8.1_mac_legacy.dmg)" macOS legacy version, and install it on MaxOS X Yosemite Version 10.10.5.

Start is denied with error, stating that I cannot start Jamulus with the current version MacOS X 10.10.5, and it would require version 10.13.

**To Reproduce**

Download Jamulus legacy version
try to install on macOS X 10.10.5

**Expected behavior**

Legacy version to run on 10.10.5

**Screenshots**

<img width="440" alt="2021-12-04 16_26_45-EIVOK Tralala _ Jitsi Meet" src="https://user-images.githubusercontent.com/78548438/144717101-7697547b-dbe5-4b5e-b886-14b1965e5c47.png">

**Operating system**

MacOS X Yosemite 10.10.5

**Version of Jamulus**

3.8.1

**Additional context**

We tried it several times, with deinstalling and re-installing. Always the same effect

**Comment by ann0see** [comment]
Maybe a wrong version was linked/downloaded? Does the latest legacy version work from here: https://github.com/jamulussoftware/jamulus/actions/runs/1507177494

(scroll down to artefacts). If this version works, probably there’s something wrong with the released assets.

**Comment by softins** [comment]
When creating the build procedure for the legacy version, we just concentrated on the version of Qt. Maybe we also needed to do something else in the build to ensure compatibility with those old versions of macOS, and to ensure that the installer would allow them. @emlynmac ?

**Comment by emlynmac** [comment]
> When creating the build procedure for the legacy version, we just concentrated on the version of Qt. Maybe we also needed to do something else in the build to ensure compatibility with those old versions of macOS, and to ensure that the installer would allow them. @emlynmac ?

I have no idea about the legacy build; 10.13 is a pretty old version of macOS and we do need to move forwards eventually.

**Comment by softins** [comment]
OK, I've just been prompted by someone to look again at this. It looks like the files `mac/Info-make.plist` and `mac/Info-xcode.plist` both specify a minimum version of 10.13, and wrongly get used when building the legacy build.

We need to work out how to provide different versions of those files when creating the legacy build, so that the minimum version can be set to 10.10

**Comment by softins** [comment]
Aha, the minimum version in the `Info.plist` was not specified in 3.8.0, and was added later, in e0cac75ee0d5ef0a6f85f6b88367abab9b659853. I have been told the legacy build for 3.8.0 installs fine on 10.10; it's just the legacy build for 3.8.1 that insists on 10.13.

@emlynmac is the minimum version specification in `Info.plist` mandatory for the signing process? For the legacy version we either need to omit it, or to script it to be 10.10 instead of 10.13.

**Comment by softins** [comment]
@georg-sch for the time being, you can install 3.8.0 instead, which you can find at https://github.com/jamulussoftware/jamulus/releases/tag/r3_8_0

**Comment by emlynmac** [comment]
It was needed iirc. Looks like we need a separate plist for the legacy version

**Comment by softins** [comment]
@georg-sch there is a legacy build of the latest Jamulus that should work, at https://github.com/jamulussoftware/jamulus/actions/runs/1669722667

Are you able to try it on the affected machine and let us know?
