### ISSUE TITLE
ASIO detected by windows installer while not installed 

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#2145]
**Describe the bug**

The windows installer believes ASIO is installed when the ASIO driver ASIO4ALL has been removed from the system.

**To Reproduce**
Install ASIO4ALL
Remove ASIO4ALL
Install Jamulus
During the installation, Jamulus does not generate a warning about no audio driver being installed.

**Expected behavior**

Jamulus should detect there is no ASIO driver installed.

**Operating system**

Windows 10 21H1
ASIO4ALL 2.15 Beta

**Version of Jamulus**
v3.8.1

**Additional context**

Seems to be caused by a registry key being left behind after the ASIO4ALL uninstall.
Perhaps a different key/value should be checked?
Current check is on: **HKLM\Software\ASIO**
In this registry key there are sub-keys per installed ASIO driver. The main key (ASIO) might be left behind by more drivers.
A possible fix could be to check if the registry contains any sub-keys or not. It is still not fool proof, but at least it is a step up in the detection.

**Comment by henkdegroot** [comment]
I am happy to work on this issue, once we agree on the solution.

**Comment by ann0see** [comment]
Thanks for raising this issue!

Yeah, I was also aware of this problem but didn’t investigate it further since I thought it’s not worth the hassle to introduce even more logic into the installer. Moreover I thought of this error message more of a one time warning for newbies who install and - hopefully- forget about ASIO4ALL. But feel free to enhance ASIO driver detection!

**Comment by henkdegroot** [comment]
Please assign this to me. FYI, this is not specific to ASIO4ALL, even though it was ASIO4ALL leading me to find this odd behaviour.

**Comment by ann0see** [comment]
Ok. Done
