### ISSUE TITLE
Server-recorded project wav filenames show full IPv6 address

### ISSUE THREAD

**Issue by rdica** [jamulussoftware/jamulus#2342]
**Describe the bug**

I recorded a jam last night and after downloading the project to my local DAW, I discovered the wav file generated by my clients connection displayed the whole IPv6 address of the client, unlike the filename of the client using legacy IP address:

```
ardy@host:~(0)$ ll Jam-20220126-234046629/
total 122472
drwxr-xr-x 2 ardy ardy     4096 Jan 27 14:44 ./
drwxrwxr-x 3 ardy ardy     4096 Jan 27 13:38 ../
-rw-r--r-- 1 ardy ardy 62696492 Jan 27 13:38 Hey_Joe_-75_163_73_x_22175-1-2.wav
-rw-r--r-- 1 ardy ardy      158 Jan 27 13:38 Jam-20220126-234046629.lof
-rw-r--r-- 1 ardy ardy     5617 Jan 27 14:44 Jam-20220126-234046629.rpp
-rw-r--r-- 1 ardy ardy 62696492 Jan 27 13:38 RickD-2001_1055_8000_df70_1ad6_c7ff_fe01_a562_x_22217-0-2.wav
```
As shown above, the legacy IP has it's last octet masked but on the IPv6 address all 8 nybbles are shown and the _x_ is masking what?

**To Reproduce**

Enable recording and IPv6 on the server, connect IPv6 client, play.

**Expected behavior**

Filenames generated by recording from IPv6 clients to have last nybble obfuscated, just as last octet in legacy IP is obfuscated.

**Screenshots**

**Operating system**

Fedora Server 34. Jamulus 3.8.1 compiled from source.

**Version of Jamulus**

Jamulus 3.8.1 compiled from source using `qmake-qt5 "CONFIG+=noupcasename headless nosound" Jamulus.pro`.

**Additional context**

**Comment by hoffie** [comment]
Thanks for the report. I've just submitted PR #2343. I'd be happy if you provided feedback there (you should be able to download release artifacts later here: https://github.com/jamulussoftware/jamulus/actions/runs/1797513379).

**Comment by rdica** [comment]
@hoffie  Thanks, I will look at this over the weekend and report back.

**Comment by rdica** [comment]
I cloned ipv6-masking branch and compiled:
```
/data/jamulus/recordings/Jam-20220205-212015025:
total 11592
-rw-rw-r-- 1 ardy ardy       92 Feb  5 16:21 Jam-20220205-212015025.lof
-rw-rw-r-- 1 ardy ardy      726 Feb  5 16:21 Jam-20220205-212015025.rpp
-rw-rw-r-- 1 ardy ardy 11860012 Feb  5 16:21 RickD-_2001_8d4_3000_ed10_1ad6_c723_7b01_xxxx__22217-0-2.wav

/data/jamulus/recordings/Jam-20220205-212220325:
total 2840
-rw-rw-r-- 1 ardy ardy      63 Feb  5 16:22 Jam-20220205-212220325.lof
-rw-rw-r-- 1 ardy ardy     639 Feb  5 16:22 Jam-20220205-212220325.rpp
-rw-rw-r-- 1 ardy ardy 2896428 Feb  5 16:22 RickD-75_160_142_x_22217-0-2.wav
```
Looks like it works.
Are the extra underscores (at start and end of IPv6 address) intentional?

**Comment by hoffie** [comment]
Thanks for the feedback!

They do look a bit strange, but they stem from the fact that the PR also adds proper `[IPv6address]:port` formatting. At the same time `[` and `]` will be replaced by underscores in the log. So... expected, but still strange.

@softins Any idea how we should handle it? I guess it would be OK to keep it like that? Otherwise it would need special handling somewhere (the translate() function maybe?).

**Comment by softins** [comment]
Yes, I expected that this would happen, but felt it more important that the output of `toString()` was correct and unambiguous for IPv6. Maybe the function that changes punctuation characters to `'_'` could do repetition squashing like `tr -s` does? It's not a major issue though, and won't affect most people, so that could wait until the next release.
