### ISSUE TITLE
Effect of MIDI fader audio changes lags behind UI changes

### ISSUE THREAD

**Issue by bawbgale** [jamulussoftware/jamulus#2492]
**Describe the bug**
Attempting to use MIDI control for the first time. Launching the Mac client with this command:
`open -a "Jamulus.app" --args --mutestream --ctrlmidich "1;f70*8"`
The effect of my MIDI controller knobs on the corresponding Jamulus fader UI controls is immediate, but the effect on the actual audio level lags behind by ~10 seconds. If I do the same action by manipulating the UI faders with my mouse, there's still a bit of lag but much less.

**To Reproduce**
For example, picking a play whose LEDs show the person playing constantly. With UI fader at zero, I quickly move the MIDI controller knob until the UI fader goes all the way to 100%. After about ~4 seconds, the player's sound level starts slowly rising, reaching full after ~10 seconds. If I do the same action by manipulating the UI with my mouse, the audio level reaches full in ~4 seconds or less.

**Expected behavior**
Manipulating the faders via MIDI should be at least as responsive as manipulating the UI via mouse.

**Screenshots**
N/A

**Operating system**
MacOS Big Sur (11.5.2) on MacBook Pro (Retina, 15-inch Mid 2014), 2.2 GHz Quad-Core Intel Core i7, 16 GB 1600 MHz DDR3 RAM

**Version of Jamulus**
3.8.2 and 3.8.1

**Additional context**
My MIDI controller is a Akai MPK mini mk3

**Comment by hoffie** [comment]
Thanks for the report.
From a quick glance, MIDI input re-uses the same logic as the UI, so I'm a bit surprised.
I'm wondering if it the MIDI controller might generate lots of events for minimal increases which creates some kind of backlog for events or packets somewhere?
To prove this, we would either need to add some kind of debug output or -- if we suspect something on the network -- a packet dump. I guess this would be the easiest. Do you think you could capture the traffic on Jamulus' UDP port 22124 shortly before you trigger the MIDI controller until the target gain value is hearable?

Not sure if `tcpdump` is readily available for Macs. If so, the following filter would help to capture protocol-only traffic:
https://github.com/softins/jamulus-wireshark/blob/master/tcpdump/capture-jamulus-proto.sh#L14

If not, a full capture on the port (e.g via Wireshark) should be OK as well.

https://github.com/jamulussoftware/jamulus/blob/b039cb8165c4ece3779e5fae1f45a68f28648ab7/src/client.cpp#L672
https://github.com/jamulussoftware/jamulus/blob/b039cb8165c4ece3779e5fae1f45a68f28648ab7/src/clientdlg.h#L142

**Comment by softins** [comment]
Bob first reported this on Facebook. This was one of my replies:
> My guess is that each time the fader level changes, even slightly, a message gets sent to the server telling it of the new level. If the Midi controller has a lot more resolution than the screen fader, it’s possible that a rapid change from 0 to 100% results in a LOT of level change messages going to the server. It has to process each one. If that is indeed the case, we should add some kind of rate limiting to it, so that a new level is only sent, say, every 200ms instead of on every single slight value change. When I get time, I’ll try monitoring the protocol traffic when doing rapid fader changes, to see if that is the explanation.

**Comment by softins** [comment]
Thinking about it a little more, a fader level change message is a connected-mode message, so needs to be acked. Does Jamulus wait for the ack for a message before sending the next queued message? If so, and a sudden big fader movement queues up say several tens of level change messages, there will be a full round-trip latency between each level change message gets sent, taking quite a while to work through the queues messages. This sounds to me like a plausible explanation, although I haven't yet observed it. A Wireshark trace would easily confirm or refute this theory.

**Comment by pljones** [comment]
The client code should be able to limit the number of messages - 128 updates plus acks on one fader shouldn't be too bad but, if the client is sending a message regardless of whether the value _actually changed_, then it could be swamping the server (and itself).

**Comment by softins** [comment]
> Not sure if `tcpdump` is readily available for Macs. If so, the following filter would help to capture protocol-only traffic: https://github.com/softins/jamulus-wireshark/blob/master/tcpdump/capture-jamulus-proto.sh#L14

I have `tcpdump` on my Mac, but I can't remember how I got it on there. The executable is less than a year old, so it certainly didn't come with it.

**Comment by softins** [comment]
> As a minimum, it needs to check whether the request is making a significant change and _do nothing_ if not.

Any change, even an insignificant one should find its way to the server. What I would do is something like this:

1. Each fader channel will have an associated one-shot timer, of say 200-250ms.
2. When a fader level changes, if the timer is running, it just locally stores the new, unsent value. Otherwise, it queues a level change message for the new value, stores the sent value for later comparison, and starts the timer.
3. When the timer fires, the unsent value is compared with the last sent value. If they differ, do step 2 again to send the unsent value, otherwise do nothing.
4. A change to the sent level caused by using the Mute or Solo buttons could be queued immediately without starting the timer (but also stopping the timer if it is running).

**Comment by hoffie** [comment]
> Any change, even an insignificant one, should find its way to the server.

Agreed.
However, if we confirm that the existing logic doesn't check for non-changes at all (as @pljones hinted), this might be a rather trivial fix, it might be sufficient (if we accept 128 (?) messages, worst-case) and it might save us from adding the timer-based approach.

**Comment by pljones** [comment]
@softins - we don't need MIDI to have a higher resolution than the client UI faders.  IIRC they have no more than 100 discrete values.  128 values for MIDI is about the same.  But generally people click on a position on the UI to change fader position, sending one new, distinct value, whereas with MIDI, the fader moves through all the values.  And because the hardware controller may be sending a "new" value each time it detects a change, it can send "changes" that aren't changes at all.

I know I recently added (on my local working branch IIRC) some checks for "if it hasn't changed, don't update" - but I'm pretty sure the logic isn't there, as the UI is "pretty safe" for these things.  Both JSON-RPC and MIDI updates of values should, however, have checks in the client code (i.e. one common place for all ways of updating a value) to prevent sending ineffective updates.

**Comment by softins** [comment]
I have done some tests with this, which confirm my initial suspicions.

I have a M-Audio Keystation mini 32, which has a single volume knob on CC #7. I connected it by USB to my Pi and in `qjackctl` selected the `raw` MIDI driver. I started Jamulus with `Jamulus --ctrlmidich '1;f7*1'`, and then in `qjackctl` I needed manually to connect System `midi_capture_1` to Jamulus `input midi`. This allowed the volume knob to control the fader for channel 0 only.

I set up packet capturing on the Pi with `tcpdump -w /tmp/jamulus-xxx.pkt -s0 host xxx.xxx.xxx.xxx and udp port 22124`, where the `xxx` depended of course on the server I planned to connect to.

Next I connected to my own 3.8.2 private server in London with a ping of about 13ms. I turned the volume knob quickly from min to max, waited a while, and then quickly from max to min. After waiting a while again, I used the mouse to drag the fader slider quickly from min to max, and then again after a pause from max to min again. In each case the time to move from min to max or back was probably no more than half a second.

For an extreme comparison, I then repeated the above test with a new packet file and a connection to a distant 3.8.2 server in Hong Kong, with a ping of around 250ms.

I examined both captures in Wireshark, displaying just the channel gain messages using the filter `jamulus.id == 13`. I could also include their acks using the filter `jamulus.id == 13 or (jamulus.id == 1 and jamulus.ackid==13)`.

I found the following:

- After sending a connected message, the client waits for an ACK before sending the next queued message. If the ACK doesn't arrive within 400ms, it sends the pending message again. There is no provision for multiple packets to be sent and acked in parallel. This is ok on low-latency connections, but could have a significant effect on more distant connections.

- I found that in fact, quite often the message would be resent without waiting 400ms (same packet counter, so not just two consecutive messages with the same gain). I think this is a bug, possibly in `CProtocol::SendMessage()`, but haven't investigated that yet.

- When connected to my London server, the MIDI controller caused around 100 level change messages to be sent, and they took almost 2 seconds to drain, as each queued message was sent after the previous one was acked.

- When connected to the Hong Kong server, the approx 100 level change messages from the MIDI controller took over 25 seconds to drain, due to the long round-trip time for acks.

- When dragging the fader using the mouse, doing so very quickly results in a lot fewer channel gain messages, presumably due to the timer resolution of the GUI only capturing fewer changes. Dragging the fader more slowly, taking say 2 or 3 seconds from min to max, results in a lot more channel gain messages, similar to the MIDI controller. In this latter case, when connected to Hong Kong, they similarly took tens of seconds to drain.

- @pljones mentioned just clicking on the desired fader position instead of dragging. This seems to work on Windows, but not on the Pi. On the Pi, it just moves the fader a small step in the direction toward the click.

So I think my theory mentioned above in https://github.com/jamulussoftware/jamulus/issues/2492#issuecomment-1065972237 is actually what's happening. I think the place to provide some kind of rate limiting, while ensuring a final steady-state gain reaches the server, is in `CClient::SetRemoteChanGain()`.

@bawbgale, when you observed this behaviour, how distant was the server to which you were connected?

**Comment by bawbgale** [comment]
@softins Great investigation! As I recall, the servers I was connecting to during my test were fairly distant, like ~150-200ms. I was doing this early AM Seattle time, and just looking for any public server with a live jam underway that I could eavesdrop upon, so those were primarily in Europe at that time of day.

**Comment by bawbgale** [comment]
@softins I just tried that build with a server 160ms away and it works much better! MIDI controller changes take effect very quickly. Thank you!
