### ISSUE TITLE
Document git rebase tutorial

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2558]
**What is the current behaviour and why should it be changed?**
Git is confusing - especially for new contributors. 
Contributors might be confused how to update their PRs and merge instead of rebase. We should explain the process of interactive rebase with conflicts.

**Describe possible approaches**

Link https://teamairship.com/update-outdated-branch-without-creating-merge-commit/ or similar somewhere or give explanations in CONTRIBUTING.md

**Has this feature been discussed and generally agreed?**

No

**Comment by pgScorpio** [comment]
I totally agree we need some clear tutorial, and the suggested link is a great starting point

Another good one is [this one](https://www.maxwellantonucci.com/posts/2017/09/24/the-git-rebase-introduction-i-wish-i'd-had/) (Though it's very lengthy and I doubt most people will actually read it all, though this is really essential. And still then not all will be clear right away.)

The point is that git is quite complex and there are many online tutorials, not all telling the same, and none of them mention all the errors you can encounter and what to do with them. (My personal experience, and I'm still having problems because I took the wrong (git suggested) actions on those errors.)

**Comment by ann0see** [comment]
Yep. Not sure which one of them is better. See #2561
