### ISSUE TITLE
Add `.gitattributes` 

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2634]
As suggested by @pgScorpio in #2585

TODO: Work out the details

**Comment by gilgongo** [comment]
Is this for 3.9.0 or shall we postpone?

**Comment by hoffie** [comment]
Not strictly release-related. If it is ready, it can get in, if it isn't, it'll be done afterwards.

**Comment by ann0see** [comment]
Da-tagged

**Comment by pljones** [comment]
Do we have any idea what's needed for this?  If not, should we close for now?

**Comment by pgScorpio** [comment]
As mentioned in the other topic:
See [here](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings) or [here](https://stackoverflow.com/questions/9976986/force-lf-eol-in-git-repo-and-working-copy).

**Comment by pljones** [comment]
Could you please write a useful post?  Those articles exist.  So this ticket isn't needed?  Or it is needed _because_ some change is required _somewhere_.  Say something that indicates where work is required _in context_.

**Comment by pgScorpio** [comment]
OK, (I thought it should already be clear from the mentioned related topics.)

As, by default, line endings are converted to the OS standard clang-format will sometimes have different results on Windows OS causing clang-format checks to fail on long line breakings for files edited and clang-formatted on Windows.
This default behaviour can be changed by the .gitconfig file, but a .gitconfig file can't be included in the repo, so everybody would have to modify or create his own .gitconfig.
But, since fixed line-endings can also be achieved with a .gitattributes file and a .gitattributes file can be included in the repo, my suggestion was to add this to the repo.
What needs to be added to the .gitattributes file to force unix line-endings can be found in the links I provided....

**Comment by pljones** [comment]
The point of having an issue in the project is to capture what applies to the project itself.  Having general articles doesn't provide that.  The issue should reference specific areas of change required, ideally referencing specific examples.

**Comment by pljones** [comment]
Not clearly defined, no bug identified, moving out to 3.10.0.

**Comment by pljones** [comment]
Closing as no progress in two years.  If the issue arises afresh, it can be looked at.
