### ISSUE TITLE
Build: Debian -dev builds (non-release) show version as -dirty

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2800]
**Describe the bug**

`jamulus-headless -v` outputs `-dirty`

**To Reproduce**

**Expected behavior**

Should not be `-dirty`.
Likely reason: The moving around of debian control files during build. Maybe symlinks would be an alternative.

**Operating system**

Debian oldstable

**Version of Jamulus**

master

**Additional context**

**Comment by ann0see** [comment]
The release?

**Comment by hoffie** [comment]
No, I think it only affects intermediate, non-release versions.

**Comment by pljones** [comment]
`-dirty` is _correct_ if a build process doesn't use the binary from an unchanged source tree.  If debian is doing something to change the source tree _before generating the binary_, that's a bug in the build process.

(That is, I don't know how the `-dirty` gets applied: but if it only happens when using the debian flow, it's the debian flow that's wrong.  It doesn't happen with `make distclean; qmake && make -j3 && make clean`.)
