### ISSUE TITLE
Autobuild: Linux ARM build fails due to dependency issues

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2837]
**Describe the bug**

The CI check for armhf fails: https://github.com/jamulussoftware/jamulus/runs/8178983224?check_suite_focus=true and the log gives a dependency error message. Probably something changed on the ubuntu repo about qt5?

**To Reproduce**
Start a armhf .deb build on GitHub

**Expected behavior**

Build executes without errors

**Screenshots**

/

**Operating system**

Ubuntu, ARMHF build

**Version of Jamulus**

/

**Additional context**

https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1209239 (not yet read)

**Comment by hoffie** [comment]
I've tried reproducing the issue and failed: The most-recent Ubuntu 18.04 image works for me. Turns out, meanwhile it works on Github as well (manually run build): https://github.com/jamulussoftware/jamulus/runs/8226397369?check_suite_focus=true

I was able to confirm that the image version with the digest `sha256:3aa2ccb021969aadb28381fee1b247422e845b176e241cd1540c4b6831e000bb` did indeed fail in that way, also when tested locally.

So the explanation is that there was a problematic ubuntu:18.04 docker image version.

If we ever encounter a similar issue, a workaround would be to revert to the previously working version by substituting `ubuntu:18.04` by `ubuntu@sha256:...digest.of.previously.working.version.from.build.logs` in `autobuild.yml`.

I was unable to find some kind of changelog for the ubuntu:18.04 docker image which might have had an explanation for this. I've quickly checked apt.sources* and did not spot anything specific.
