### ISSUE TITLE
Suggestion of adding 'positional audio' of instruments or choir sections

### ISSUE THREAD

**Issue by kezzy1966** [jamulussoftware/jamulus#567]
This is a great feature from the 'low latency' Mumble audio protocol developed for gamers to communicate while 'in game' and moving around as a platoon shooting the enemy. The player spoke from a position relative to your position in the game. 

Wondered if you guys could consider the idea of having this concept in Jamulus. With stereo headphones on,  one could hear the sound of the lead guitar coming more from the left and the bass guitar more from the right, with drums in front and the singer behind you for example. It could be an amazing immersive experience.  

Likewise if choirs could have all the 'tenors' in one audio space, Bass in another etc. 

Not sure how you would manage 'positions' but I'll that to the cleaver ones to work out. Mumble is open source so you could see how they do it.

I refer to 'Positional Audio' here: 
https://wiki.mumble.info/wiki/Features

**Comment by ann0see** [comment]
Do you mean panning? It should already be available if you enable mono-in/stereo out and have a modern jamulus server running v

**Comment by kezzy1966** [comment]
Ann0see, well 'pan' is half of it. In Mumble you also have in front and behind you. 
So rather than an up/down slider for 'pan', you would might have a cross or an 8 point star to position your audio.

**Comment by ann0see** [comment]
I‘m quite sure you can move people behind you too. But do you mean that you can also move sb. towards/away from you?

**Comment by corrados** [comment]
There is a Git branch available which implements a delay pan (https://github.com/corrados/jamulus/issues/332). I have not tried it myself but Detlef Hennings (http://www.climate-one.de) did some tests with it for the intention to be used with choirs. It should have a similar effect as far as I understood.

Implementing a positional audio is usually done using an [HRTF](https://en.wikipedia.org/wiki/Head-related_transfer_function) which means that both stereo signals are filtered. This filtering would have to be calculated in the Jamulus server which increases the processor load. Also, since Mumble is intended for voice only, Jamulus is intended for musical instruments. I am pretty sure that the HRTF filtering will change the sound of the instrument significantly which most musicians would not want.

**Comment by kezzy1966** [comment]
Hi Corrados,
I do not agree. I found that Mumble and its rebirth as Mumla (Swedish for Mumble as the Swedish team took over development) has outstanding audio if you turn the audio quality up. I think it could easily handle instrument frequencies.

**Comment by corrados** [comment]
> outstanding audio if you turn the audio quality up. I think it could easily handle instrument frequencies

I have not tried to use Mumble for online jamming. Maybe I should give it a try someday.

**Comment by kezzy1966** [comment]
...unfortunately Mumble delays are too long. The coders confused 'ping times' for 'overall delays'. It does not work for jamming sessions.

**Comment by Hk1020** [comment]
What happened with this patch #332 ? I just tried it and I like the result very much. The only missing part I see is a command line option and maybe a signal to turn delay panning on or off.

**Comment by ann0see** [comment]
Not sure unfortunately. If it doesn't give any disadvantages and somebody updates the code, I don't think that this can't be implemented.

**Comment by Hk1020** [comment]
> 
> 
> Not sure unfortunately. If it doesn't give any disadvantages and somebody updates the code, I don't think that this can't be implemented.

Ok, I'll have look unless someone beats me.

> 
> Maybe
> 
> > This filtering would have to be calculated in the Jamulus server which increases the processor load.
> 
> is a problem. We should keep the load on the server as low as possible.

But as this is optional I don't think it will be a problem. And from a first look at the code it doesn't seem to be very strenuous.

We need a command line option, though, to turn it on or off and maybe a signal as well.

**Comment by hoffie** [comment]
> Ok, I'll have look unless someone beats me to it.

Cool! The other ticket seems to refer to an [even newer code base](https://github.com/jamulussoftware/jamulus/tree/feature_hennings_delay_pan2). The [diffs](https://github.com/jamulussoftware/jamulus/commit/e31ab0a318ec6fdf868c84afd573e402d09b1cfb) look really huge, I suspect there are some white space issues which may make merging/rebasing hard. :(

Maybe passing both the commit before and the actually relevant commit through a [formatter](https://github.com/jamulussoftware/jamulus/pull/1127) may help to get a useful diff.

**Comment by Hk1020** [comment]
> 
> 
> > Ok, I'll have look unless someone beats me to it.
> 
> Cool! The other ticket seems to refer to an [even newer code base](https://github.com/jamulussoftware/jamulus/tree/feature_hennings_delay_pan2). The [diffs](https://github.com/jamulussoftware/jamulus/commit/e31ab0a318ec6fdf868c84afd573e402d09b1cfb) look really huge, I suspect there are some white space issues which may make merging/rebasing hard. :(

I am working from there and there are white space issues. `git show -p e31ab0a3 -w` shows you the actual change. Unfortunately, the code has evolved quite a bit since then so this patch doesn't apply anymore. I am working my way through the code history. I should be getting there.

> 
> Maybe passing both the commit before and the actually relevant commit through a [formatter](https://github.com/jamulussoftware/jamulus/pull/1127) may help to get a useful diff.

I don't know how to use this but I think I am fine with pure git (see above).

**Comment by Hk1020** [comment]
I am done with it. I successfully reworked #332 and can now compile the modified version. It works just like the original patch.

As I've never created a pull request on github I am not sure how to proceed. I forked Jamulus and put the code on a new branch and pushed it into my repository. What next?

I'd like to add a command line option and we might want to discuss if delay pan should be on by default, which it currently is. I am also thinking of making this a client setting but I need to check if it is possible. So this means there might be further commits. Again, how to handle them?

**Comment by hoffie** [comment]
> I am done with it. I successfully reworked #332 and can now compile the modified version. It works just like the original patch.

Cool! :)

> As I've never created a pull request on github I am not sure how to proceed. I forked Jamulus and put the code on a new branch and pushed it into my repository. What next?

Then you're almost done. ;)
The `git push` will probably have mentioned an URL to open a pull request. If you don't have the output, no worries.

You can just go to Github, select your fork, select the branch and Github will most likely provide the option to open a PR. You'll probably end up here: https://github.com/jamulussoftware/jamulus/compare/master...Hk1020:delay_pan?expand=1

I'd suggest to submit it as a Draft PR though (there's a small link on the right side when opening a PR) if you intend to add further code.

> I'd like to add a command line option

This should be rather simple as one can easily borrough existing code for option handling. :)

> we might want to discuss if delay pan should be on by default

I haven't tried this feature, but definitely will. Not sure about changing defaults though. I guess others will comment on that.

> I am also thinking of making this a client setting but I need to check if it is possible.

This would probably mean introducing a protocol message so that clients could signal their intend to the server? This might be a bit more sophisticated and I'm not sure if one wants different pan algorithms on the same server? May be also something for later improvement after the feature has landed?

> Again, how to handle them?

As long as no PR has been created or merged, you can just push them to your fork's branch. If your PR is ready you should only push commits to your branch which address review comments in the PR.

Hope this helps.

**Comment by Hk1020** [comment]
> 
> 
> > I am done with it. I successfully reworked #332 and can now compile the modified version. It works just like the original patch.
> 
> Cool! :)
> 
> > As I've never created a pull request on github I am not sure how to proceed. I forked Jamulus and put the code on a new branch and pushed it into my repository. What next?
> 
> Then you're almost done. ;)
> The `git push` will probably have mentioned an URL to open a pull request. If you don't have the output, no worries.
> 
> You can just go to Github, select your fork, select the branch and Github will most likely provide the option to open a PR. You'll probably end up here: https://github.com/jamulussoftware/jamulus/compare/master...Hk1020:delay_pan?expand=1
> 
> I'd suggest to submit it as a Draft PR though (there's a small link on the right side when opening a PR) if you intend to add further code.

I already saw this but just didn't understand yet how it works. I'll make a draft real soon now.

> 
> > I'd like to add a command line option
> 
> This should be rather simple as one can easily borrough existing code for option handling. :)

No problem to do it. I was rather wondering if this should be a separate commit, which I think it should, or if you prefer a single, possibly squashed commit.

> 
> > we might want to discuss if delay pan should be on by default
> 
> I haven't tried this feature, but definitely will. Not sure about changing defaults though. I guess others will comment on that.

I'll leave it off then. This is different from the original patch.

> 
> > I am also thinking of making this a client setting but I need to check if it is possible.
> 
> This would probably mean introducing a protocol message so that clients could signal their intend to the server? This might be a bit more sophisticated and I'm not sure if one wants different pan algorithms on the same server? May be also something for later improvement after the feature has landed?

I looked at it in the meantime and it shouldn't be hard to do on the server side. Panning is done individually per client anyway and the way this has been implemented there is a boolean in the mix which could just be set by the client. I need to investigate the protocol message stuff.

> 
> > Again, how to handle them?
> 
> As long as no PR has been created or merged, you can just push them to your fork's branch. If your PR is ready you should only push commits to your branch which address review comments in the PR.

Good, the client stuff will be a separate PR then to get this flying. I'll just add the command line option and make the PR.

**Comment by Hk1020** [comment]
One more question. How do you do translations? There is new checkbox on the server config which now reads _Enable delay panning_ and I think this should be translated.

**Comment by hoffie** [comment]
>  I need to investigate the protocol message stuff.

It's not rocket science, but when touching protocol parts we have to be extra sure to remain backwards-compatible.

> Good, the client stuff will be a separate PR then to get this flying. I'll just add the command line option and make the PR.

Cool! Yeah, I suggest creating a minimal PR so that people like me can test it. We should then wait for some more comments by other contributors/maintainers.

> How do you do translations?

If you are using messages in the code, be sure to use the `tr ( )` function. If this is in a `.ui` file I think it will be translateable by default (maybe @ann0see can confirm?). Besides that, you don't have to do anything for translations. When your PR is agreed on and merged, it will become part of the next Jamulus release (i.e. 3.7.1 or something). Before rolling a new release, translators will be asked to provide translations for all newly added strings. No TODOs for you, this is handled as part of the release process.

**Comment by ann0see** [comment]
> If you are using messages in the code, be sure to use the tr ( ) function. If this is in a .ui file I think it will be translateable by default (maybe @ann0see can confirm?)

I'm not sure about the .ui thing, but in the code this should be true.

**Comment by hoffie** [comment]
> I'm not sure about the .ui thing

Just ran a quick test: I edited a .ui file and added a new widget. I then ran `lupdate Jamulus.pro` and the translation files now contained the new widget's label. It looks my assumption was right.

**Comment by passing** [comment]
I'm really looking forward to trying this new feature!

One thing that came to my mind: maybe it would be desirable, if clients could opt-in/out individually from getting "Delay Panning" from a server that supports it. Otherwise you may struggle with finding a server for your rehearsal that has a good ping and your preferred panning configuration (which may also be different between band members)

https://github.com/jamulussoftware/jamulus/pull/1151#discussion_r584631198

**Comment by hoffie** [comment]
> if clients could opt-in/out individually from getting "Delay Panning" from a server that supports it.

It would require additional protocol and implementation logic in critical code paths though. I would suggest opening a new Discussion for that to find out if and why there would be demand for that. There is still a way to "avoid" delay panning by choosing "Mono" mode (where it is possible).
