### ISSUE TITLE
Auto window sizing fails on Mac with vertical monitor

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulus#671]
![Screen Shot 2020-10-11 at 12 12 01 PM](https://user-images.githubusercontent.com/47258736/95687844-0bd17b80-0bbb-11eb-809a-88e2491a7dde.png)

Screen shot attached.  On Mac with vertical monitor orientation.  Starting Jamulus results in immediate resizing, but (1) window is not placed at top of available area (just below Menu Bar) and (2) window is sized too large (horizontally) to fit on screen.

**Comment by corrados** [comment]
Have you started Jamulus in horizontal orientation and closed Jamulus. Then you have changed the orientation of your monitor and started Jamulus again? Because Jamulus stores the window size/position of the last session. It does nothing about orientation of your monitor.

**Comment by chrisrimple** [comment]
On a Mac.  I have 2 monitors: my primary monitor is vertical, my secondary is horizontal.  Linked below are screen recordings of the behavior I'm seeing from Jamulus when running it on each monitor, which includes:

1. Every time I start Jamulus (on vert or horiz), it's not restoring the prior window position.  Instead, it's resizing itself to default/small.  This is new behavior in 3.5.12; previously, I believe that it was restoring window size and position.
2. Every time I start Jamulus on my horiz monitor (which is secondary), the window opens on my vert monitor (primary).
3. I have Tabs enabled in MacOS.  Every time I start Jamulus, it sizes the window for 2 tabs, Settings and Chat, sets the window position, and then adds a tab for the Mixer.  When starting Jamulus on my horiz monitor, the window that opens on my vert monitor is partially off-screen as as result.

My computer is a laptop.  When using the internal monitor, I'm seeing #1 and #3 (sizing for 2 tabs, then adding 1) as well.

Screen recordings at https://drive.google.com/drive/folders/196PeuV6kyLbRGZPBvHGr8YPww2_3dh2d?usp=sharing

**Comment by corrados** [comment]
To restore the window positions, I am using the Qt functions [saveGeometry](https://doc.qt.io/qt-5/qwidget.html#saveGeometry) and [restoreGeometry](https://doc.qt.io/qt-5/qwidget.html#restoreGeometry). So, it is all implemented in Qt and not in Jamulus.

I am using a very old Mac Mini (2009 model) when I create binaries for the official Jamulus releases. I assume that my x-code is pretty outdated and also the Qt version is old. If anybody has a newer Mac available and is able to compile Jamulus with the newest x-code and Qt, it would be great if he could create a binary and post it here as a zip-file for testing. Would be interesting to see if the problem is solved with such a binary.

**Comment by ann0see** [comment]
@chrisrimple is this issue still appearing with the latest version of Jamulus? Maybe the upcoming Qt 6 support solves this issue. At least I hope so. 

Please close this issue if you can't reproduce the bug anymore.

Note: I will unsubscribe from this issue and won’t receive responses from any new comments. If you have any questions concerning maintenance, feel free to ping me.

**Comment by chrisrimple** [comment]
I no longer have a monitor in a vertical orientation, so I'm unable to test this.  Closing, and someone can reopen if it's still an issue.
