### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by abbanatic** [jamulussoftware/jamulus#764]
Hi,

please be so kind to think about providing iOS support for Jamulus in the future.

Due to Apple's change from Intel to ARM, universal binaries for all of Apple's platforms became reality.

So it would be great for Jamulus to support the New Apple Silicon AND iOS devices, with their great built-in capabilities regarding Audio and MIDI.

Thank you very much!
Thomas

**Comment by ann0see** [comment]
Agree. Porting should be possible but there would still be the same two problems like for Android (which is in development):

1. how to deal with WiFi (of course you could use USB to LAN adapters)
2. How to deal with Audio Interfaces (iOS uses CoreAudio, so does macOS)

Something iOS specific:

Submitting to the AppStore would require Jamulus to be dual licensed. Apple doesn't like the GPL.

**Comment by ann0see** [comment]
First of all, I don't have any knowledge of iOS development. Therefore somebody experienced should look at this issue. I created a new iOS folder, edited the .pro file and copied the macOS files in there. I made some tests:

I tried to compile Jamulus with QT Creator for iOS and it (of course) failed. 

`In file included from /.../jamulus/ios/sound.cpp:25:
/.../jamulus/ios/sound.h:70:5: error: unknown type name 'AudioDeviceID'; did you mean 'AudioFileID'?` 

Will probably be one of the main issues. 

also in client.h the include statement has to be changed to ask if it's being built for iOS.

**Comment by gene96817** [comment]
Apple announced at WDC2020 some kind of merging macOS and iOS for 2021. I don't follow the details in this area closely. This suggests people interested in iOS support should look at the developer's tools for macOS 12.x.x and this "merger" with iOS. Of course, this doesn't solve the needs of devices that run old iOS release.

**Comment by ann0see** [comment]
I got a headless Jamulus server up and running on my iPhone SE 1st gen (although it's connected via wifi, the quality is ok). Everything GUI related doesn't work and also I assume files can't be written because of the iOS sandbox.

**Comment by ann0see** [comment]
https://developer.apple.com/documentation/avfoundation/avaudiosession?language=objc in https://developer.apple.com/documentation/avfoundation/avaudiosessionmodemeasurement mode could be a good choice for audio in iOS. Does anybody know anything about iOS Audio/iOS CoreAudio?

**Comment by ann0see** [comment]
Although I have no idea how to write the sound.cpp or sound.h files or StoryBoard files etc. have a look at my changes: 

https://github.com/ann0see/jamulus/tree/patch-3

**Comment by ann0see** [comment]
Anybody else here knowing iOS development and QT? Unfortunately I have almost no idea how the csound class should look like on iOS since it seems as if we can't use the same code line on macOS. 

@corrados what are the main methods for a sound.h/sound.cpp file? 

Did I find the correct ones in my code?

**Comment by corrados** [comment]
Is this still work in progress? Or shall I remove the label?

**Comment by ann0see** [comment]
You should remove the label (but I will probably continue working on some of this stuff once the installer and autobuild stuff works)

**Comment by ann0see** [comment]
Current open issues here:

1. Write sound driver for iOS
2. Fix the GUI: Currently if you launch Jamulus on iOS (after having it compiled via Xcode), it displays the "Would like to access your microphone" screen but doesn't show anything else. I think the problem is related to some settings in Xcode I don't know. There's almost no documentation for Qt widgets applications on iOS and I don't think a Qt widgets app would ever get into the AppStore.
