### ISSUE TITLE
Mute myself and mute own channel leads to sound coming back to headphones

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#909]
@mulyaj discovered a bug:

Steps to reproduce:

1. Click the "mute myself" button
2. Click the "Mute" button on your own channel in the mix

Actual behaviour:

You hear sound coming back from the server (it's local monitoring)

Expected behaviour

No sound coming back from the server

**Comment by DominikSchaller** [comment]
The sound is actually not coming back from the server, it's direct monitoring and I believe it's a feature not a bug.

**Comment by ann0see** [comment]
Ah. Interesting. But that shouldn't be the case if you're muted in your own mix.

**Comment by DominikSchaller** [comment]
I believe the mixer is always referring to the sound coming from the server and as you are not sending anything the mute button has nothing to mute. I wonder what the use case would be in which you are playing but nobody (not even you) should here it.

**Comment by DavidSavinkoff** [comment]
I'm using Janulus 3.6.2 on linux which works correctly (not like you mention), and as expected. Please give more details.

**Comment by ann0see** [comment]
Yes. Can verify that it's not coming from the server. 

> I believe the mixer is always referring to the sound coming from the server and as you are not sending anything the mute button has nothing to mute.

I think Me and mulyaj just fell through an issue @gilgongo mentioned (mixing board analogy).

I'm using 3.6.2git (not sure which commit I used to compile it).

**Comment by chrisrimple** [comment]
I've just tested this on 3.6.2, on a server for which I have 200ms Overall Delay...

1. MUTE MYSELF = false and MUTE = false.  I DO hear myself returned from the server.
2. MUTE MYSELF = false and MUTE = true.  I DO NOT hear myself returned from the server.
3. MUTE MYSELF = true and MUTE = false.  I DO NOT hear myself returned from the server.  I DO hear myself locally.
4. MUTE MYSELF = true and MUTE = true.  I DO NOT hear myself returned from the server.  I DO NOT hear myself locally.  In other words, I hear nothing.

I believe that all above is "as expected".

**Comment by ann0see** [comment]
Ok. Just trying to compile the latest version from master. Will reverify if this "solves" the issue.

**Comment by ann0see** [comment]
I could now also reproduce the other behaviour: Click on mute and then on mute myself.

**Comment by pljones** [comment]
Does the order of doing it matter?  i.e. If you had "Mute myself" on when you clicked mixer mute, is it the same effect as if you had mixer mute on and clicked "Mute myself"?

**Comment by mulyaj** [comment]
What happened exactly was the following:

- @ann0see and I were in a Jitsi call together, and were both using screen share with audio muted
- We were both in the same Jamulus server
- My personal mix was muted first and after when I enabled Mute Myself, the personal mix mute was overrided and MUTE = false

**Comment by pljones** [comment]
1. Connect to a distant server
![image](https://user-images.githubusercontent.com/1549463/106209381-d201a080-61bc-11eb-93e7-f833ce96691e.png)
2. Neither mixer mute nor mute myself - can hear audio from the server
![image](https://user-images.githubusercontent.com/1549463/106209448-f2315f80-61bc-11eb-8586-a38ac107ba80.png)
3. Mixer mute only - cannot hear audio, although the server can
![image](https://user-images.githubusercontent.com/1549463/106209516-0ecd9780-61bd-11eb-9ddb-75bef7352f8c.png)
4. Mixer mute still on, add Mute myself - cannot hear audio: nor can the server
![image](https://user-images.githubusercontent.com/1549463/106209583-302e8380-61bd-11eb-9e85-64431b683559.png)

**Comment by pljones** [comment]
More tests...

Does it make a difference if only one user has connected to the server?

Does it make a difference if the user joins an existing session?

Does it make a difference if another user then leaves the session (leaving more than one user)?

Does it make a difference if another user then leaves the session (leaving only one user)?

**Comment by DavidSavinkoff** [comment]
I compiled the latest jamulus-master.zip (3.6.2dev-) and compared it to my installed jamulus 3.6.2 and found that Both work 'as expected' (as chrisrimple shows above).
Thus, there is no regression (and no problem either) from my point of view.

The testing both versions used 'the same personal configuration'. Maybe this problem depends on how you set up Jamulus or your computer.


Note: that I came across this new build message with jamulus-master.zip 3.6.2dev-
(did not affect building) :

qmake-qt5 Jamulus.pro
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Project MESSAGE: building an intermediate version: 3.6.2dev-
Project MESSAGE: Jack Audio Interface Enabled.

**Comment by ann0see** [comment]
@nefarius2001 

> Note: that I came across this new build message with jamulus-master.zip 3.6.2dev-
(did not affect building) [...]

Can we just check if the code is a git repo and if not, just skip it?

**Comment by nefarius2001** [comment]
Hi @DavidSavinkoff , thanks for reporting the qmake issue!

=> Fix Pull Request: #956

**Comment by passing** [comment]
I think the "Mute Myself" option in the input can confuse users easily as it doesn't make clear what it actually does.
It would be nice to have a better indication in the UI to tell that users that it either "Sends sound from microphone to server" or "Sends sound from microphone to your headphones directly".
There could be even a third state which actually does mute the input ("Send sound from microphone to nowhere"). That third option would be especially helpful in some situations where a user has created a feedback loop.

**Comment by gilgongo** [comment]
@passing My suggestion has been a "Transmitting" checkbox or toggle switch. You can see an example of it incorporated in https://github.com/jamulussoftware/jamulus/issues/958#issuecomment-779032451

**Comment by dyfer** [comment]
I can confirm that sometimes the self volume level is not picked up properly when "mute myself" is activated. I'm on macOS. My audio interface has 6 ins/outs (not sure if that makes any difference).

I have indeed experienced this issue - local monitoring _starting_ after clicking "mute myself". My channel mute was _not_ selected, but my self volume was all the way down:
<img width="622" alt="Screen Shot 2021-03-22 at 10 19 22" src="https://user-images.githubusercontent.com/1589177/112031348-7686cb80-8af8-11eb-9d2c-5afa1781b43e.png">

Here's my reproducer:
- connect to a server
- turn self volume all the way down
- go to settings, change input channel mapping (e.g. from the microphone input to another input, then change it back to microphone)
- check "mute myself"

After following these steps, I can hear direct monitoring, even though the self volume is all the way down. 

If I adjust self volume, my direct monitoring level is adjusted accordingly, but the initial level doesn't seem to be picked up after the input has been switched.

**Comment by chrisrimple** [comment]
I still wonder if this is a feature and not a bug.  Someone (@corrados?) should clarify the original intent of Mute Myself.  Should it:

1. - Stop sending my sound to the server, but still let me hear it
2. - Stop sending my sound to the server and not let me hear it
3. - Send my sound to the server but not let others hear it, and still let me hear it
4. - Send my sound to the server but not let users hear it, and not let me hear it

Also, it would be good to have someone (@ann0see?) look at the code to tell us what's happening today, regardless of the original intent.  THEN we can figure out what we want to happen, and adjust the code if needed.

**Comment by dyfer** [comment]
I'd argue that my particular reproducer does _not_ seem like intended behavior: I have my fader all the way down so I should _not_ hear myself, after turning on "mute myself", but I do.

**Comment by DominikSchaller** [comment]
1. is the intended behavior. Volker wrote is somewhere months ago.

Chris Rimple ***@***.***> schrieb am Mo., 22. März 2021,
18:39:

**Comment by chrisrimple** [comment]
@dyfer I think that depends on what's intended.  If my #1 or #2 are intended (stop sending my sound to the server), then server-side fader controls shouldn't be expected to have any impact on a "local echo" that's being provided when I Mute Myself.  But your results imply that, even with Mute Myself enabled, sound is still going to the server (my #3 and #4), which (if intended) does indicate that you've found a bug.

Someone has just posted that my #1 is the intended behavior, based on a prior comment from @corrados.  If that's true, then I'm surprised that your server-side fader controls have any impact at all.  Maybe that's a bug.

**Comment by dyfer** [comment]
@chrisrimple it seems that the own level fader is indeed controlling the direct monitoring level when "mute myself" is turned on. I can't comment if this was intended behavior or not, but it does make sense to me - at least it allows to adjust direct monitoring level.

However, the **initial** level of input monitoring is sometimes not picked up properly, after the input mapping was changed.

**Comment by chrisrimple** [comment]
Going back to my comment above from 28Jan (https://github.com/jamulussoftware/jamulus/issues/909#issuecomment-769383616), I see that my tests confirmed that the server-side controls do impact the "local monitoring" when Mute Myself is enabled.  That seems wrong to me (although I called it "expected behavior") at the time.  If I wanted controls for local monitoring during Mute Myself, I think those should be new controls that don't exist in the UX today.

But I could be convinced otherwise, for simplicity.  I just worry that we've been improving the UX to clarify the Local Side v. Server Side, and continuing to adjust Local Side sound via Server Side controls is "wrong".  Granted, it's only for the single user and only during Mute Myself, so maybe that exception is OK.

**Comment by dyfer** [comment]
> Granted, it's only for the single user and only during Mute Myself, so maybe that exception is OK.

My reproducer also applies if more users are connected.

**Comment by gilgongo** [comment]
> I still wonder if this is a feature and not a bug. Someone (@corrados?) should clarify the original intent of Mute Myself. 

I've always thought it was intended to be 1 so that you could set up without bothering others ("Stop sending my sound to the server, but still let me hear it"). It would not be 3, since that would mean you would not be hearing your sound from the server.

**Comment by chrisrimple** [comment]
@dyfer I definitely think you've identified a bug that impacts all Server Side sound.  Probably a good idea to log that as a separate Issue, so that it can be addressed separately from this larger UX/expected behavior issue.

My point was that, with Mute Myself enabled, allowing Server Side controls to affect Local Side sound "breaks" the UX, but maybe that's OK since it's only breaking the UX for the Local Side user.

**Comment by dyfer** [comment]
I really don't think this is about Server Side sound. I'm sorry, I don't know how I can make myself any clearer. Have you tried my reproducer?

> Here's my reproducer:
> 
> - connect to a server
> - turn self volume all the way down
> - go to settings, change input channel mapping (e.g. from the microphone input to another input, then change it back to microphone)
> - check "mute myself"
> After following these steps, **I can hear direct monitoring**, even though the self volume is all the way down.

**Comment by dyfer** [comment]
> I really don't think this is about Server Side sound. I'm sorry, I don't know how I can make myself any clearer. Have you tried my reproducer?
> 
> > Here's my reproducer:
> > 
> > * connect to a server
> > * turn self volume all the way down
> > * go to settings, change input channel mapping (e.g. from the microphone input to another input, then change it back to microphone)
> > * check "mute myself"
> >   After following these steps, **I can hear direct monitoring**, even though the self volume is all the way down.

EDIT: I understand the point about the UI, but I believe my issue is separate from that.

**Comment by chrisrimple** [comment]
@dyfer My point is that:

- If the "correct" behavior is that Server Side controls should have no impact on Local Side sound, then what you're reporting is not a bug and is expected behavior
- But if we accept that, for Local Side sound only, we'll "break" correct behavior and allow Server Side controls to impact Local Side, then what you're reporting IS a bug

So we need to reach a conclusion about "correct" behavior, then we can address your reproducer.  :)

**Comment by DavidSavinkoff** [comment]
Simply put; this is a bug, only, if you can prove that it is a regression from previous behaviour.
Otherwise, this feature was accepted by all for a long time.
There are some new people that think old features are bugs.
It is not Jamulus at fault here.

**Comment by dyfer** [comment]
@DavidSavinkoff @chrisrimple I am _not_ reporting that the current behavior is unexpected or that it has changed from the previous version.

My report is about _inconsistency_ between turning on "mute myself", depending on whether the input mapping was changed or not in the process. Currently the observed behavior is:

- connect -> turn channel volume all the way down -> turn on "Mute myself" - > no direct monitoring (as expected)
- connect -> turn channel volume all the way down -> change input mapping -> turn on "Mute myself" -> direct monitoring is at full volume
  - channel volume is still all the way down 
  -  this is inconsistent with the scenario that does not switch input mapping

> So we need to reach a conclusion about "correct" behavior, then we can address your reproducer. :)

If you would kindly try the reproducer, it might be easier for you to understand the issue that I'm reporting. Your responses do not indicate that I managed to communicate what the issue is, but I really tried.

**Comment by ann0see** [comment]
Yes, I can also reproduce this on Debian 10. It does give an interesting hint: If you reload the audio processing, it seems as if this resets (and doesn't save) the fader levels?

**Comment by chrisrimple** [comment]
@dyfer I believe that we understand the issue that you're reporting.  My point continues to be that your first bullet (no change to input mapping), which you list as "expected behavior", is maybe not "expected" given my points about UX inconsistencies.  So there's likely a bug, but maybe it's your first bullet, not your second bullet.  I think we first need to agree on "expected behavior" (and not just assume that "what it does today" is "expected") before deciding which bullet is the bug.  :)

**Comment by dyfer** [comment]
Thanks @chrisrimple 

Regarding "expected behavior": if the server side settings should not change the input monitoring setting, then the question is what should the input monitoring level be when "mute myself" is active? I'd personally be fine with "mute myself" _not_ activating direct monitoring at all, but this would be a change in behavior from what it is currently.

Thanks @ann0see for confirming!

**Comment by DavidSavinkoff** [comment]
The expected behaviour was that you mute yourself from others, not yourself. Thus, when you are not connected to a server you can hear yourself. Your scenario is not practical as it only addresses someone's sense of orthogonal aesthetics when they have muted themself and are not connected to a server.

**Comment by chrisrimple** [comment]
@dyfer Hearing oneself when Mute Myself is enabled is very valuable to many musicians using Jamulus:

- Join a server for an Open Jam but don't want to interrupt people that are already playing
- Play along with an Open Jam but aren't skilled enough (or duplication of instruments), so Mute Myself to enjoy playing without interrupting the others
- Check or adjust my input levels without bothering others on the same server
- Experimenting with Jamulus for the first time, joining random servers, and don't want to interrupt

And so on.  Many Jamulus users would be disappointed if Mute Myself did not result in local monitoring.

**Comment by dyfer** [comment]
@chrisrimple I understand this is useful for many people and I don't insist on removing it. However, I also think that there should be an option to not have direct monitoring on when "mute myself" is turned on. Many audio interfaces already have the direct monitoring functionality, which makes software monitoring superfluous.

**Comment by chrisrimple** [comment]
@dyfer When running Jamulus, the golden rule is "always disable direct monitoring in the audio interface and any software", so that the user only hears sound returned by the server.  This prevents sync issues, when musicians are listening to direct monitoring (with effectively zero latency) and not playing along with server sound (which may have considerable latency).

That said, I don't disagree with your desire to have a way to disable direct monitoring with Mute Myself.  I don't personally see the use case, but can believe that it's valuable to some users.

**Comment by dyfer** [comment]
Splitting hairs here, but the "prevent sync issues"  might or might not apply when using "mute myself" - in that case direct monitoring is not going through the server and is therefore not delayed accordingly (as far as I can tell).

As for the use case - this is about direct monitoring in general and the users who accidentally connect with speakers turned on: in that case one gets echo, in which case the user might just want to "mute themselves" to avoid the echo. But, with direct monitoring on, this creates feedback locally. Not a "proper" use case, but definitely something I have experienced.

**Comment by dyfer** [comment]
Sorry for extending this conversation - I don't want this to be about "this is what the functionality is supposed or not supposed to be". I'm just reporting that the level/functionality of direct monitoring might differ depending on whether "mute myself" is on or off.

**Comment by DavidSavinkoff** [comment]
#909 is answered by jamulus/ChangeLog:

### 3.5.1 (2020-04-18) ###

- added a Mute Stream button to hear your signal and the signal of the other clients but
  do not transmit your signal to the server so that the other clients cannot hear you

**Comment by ngocdh** [comment]
> Yes, I can also reproduce this on Debian 10. It does give an interesting hint: If you reload the audio processing, it seems as if this resets (and doesn't save) the fader levels?

Team, this seems to be correct.

Also, if this is a feature, not a bug, then we should change the feature. Because it makes no sense to have "mute" activated twice in two different places but still hear one's voice. 

So my workaround when this happens when I just want to listen to people play music without the noise from my background is to disable and then enable again my "Mute" button in the mixer.

**Comment by DavidSavinkoff** [comment]
Reply: @ngocdh
>> @ann0see
> > Yes, I can also reproduce this on Debian 10. It does give an interesting hint: If you reload the audio processing, it seems as if this resets (and doesn't save) the fader levels?
> 
> Team, this seems to be correct.

In Linux; is this a 'Debian only' issue or are other Linux affected?

It appears that @dyfer can create this issue on MacOS by changing the microphone switching matrix (or whatever it's called in 'personal computer lingo')... interesting.

> Also, if this is a feature, not a bug, then we should change the feature. Because it makes no sense to have "mute" activated twice in two different places but still hear one's voice.

Understood, however, others and I don't experience this.

> So my workaround when this happens when I just want to listen to people play music without the noise from my background is to disable and then enable again my "Mute" button in the mixer.

- Workaround... very interesting. Maybe this can lead to a solution! (disable/enable --> initialization ???)
- Also, given what @dyfer did on MacOS, maybe this is a 'Jack issue' on Linux.
- Maybe a Debian issue

**Comment by ngocdh** [comment]
Oh not just Debian, I have it on my devices (iOS, Android and Mac). Just tested on Mac today, and strange that in this one room my workaround didn’t even work, worked on other rooms...

**Comment by jregener62** [comment]
I see this issue too as a side effect of [#1935](https://github.com/jamulussoftware/jamulus/issues/1935). In cases where I see the issue no edits of my own channel take effect anymore, including 'mute' of my own channel. I'll try to create a reproducible configuration and report in [#1935](https://github.com/jamulussoftware/jamulus/issues/1935)

**Comment by ann0see** [comment]
I think we've fixed this a few versions ago.
