### ISSUE TITLE
Gain / Input-Volume  control

### ISSUE THREAD

**Issue by jugo6** [jamulussoftware/jamulus#937]
Development question on Input-Volume Control: 

Problem:
I work a lot with choirmembers who just have a headset and nothing else. It works, and often sounds still reasonably ok. However controlling the input volume is quite a hassle. (esp. In windows). Wouldn't it be nice just to have a neat input slider at the left, preferably also to +12dB? It will also be helpful to a few softer mic/interface combo's I heard of, and avoid the hassle of extra screens, interface-mixer windows etc..... Not everyone is a guitarist with a volume knob....
And using the S-word: Sonobus has it...😁😈 And every decent analog mixer controls the input.

What is further going wrong :
 people expect it that much, that they start messing with the Pan or Reverb attempting to control their gain....

Solution:
- A Slider at the input- side in between L/R lights
Possibly in another color

- possibility to increase input above 0dB (+12dB) 

Alternative: a gain turning knob

Additional:
Perhaps make the Pan more intuïtive by being horizontal or also a turning knob, with "My Pan"
because up-down never feels like L/R

**Comment by ann0see** [comment]
Hi @jugo6. Thanks for your feature request!

I moved your issue from the website repo to the code repo so that others see it!

> Perhaps make the Pan more intuïtive by being horizontal or also a turning knob, with "My Pan"

Although this is another issue, I think the designer team is currently thinking about this. Thanks for raising this issue!

~~~

Concerning the problem of loud/quiet headsets. Yes, we (my choir) also have issues like that and the choir leader mistook pan for it too (it seemed to do what he expected and didn't actually move the mix anywhere at least according to him), so in general I support your feature request and idea behind it.

The problem with adding a feature like this (= probably duplicate feature) would be, that it might be out of scope of Jamulus (not sure though) since to some extent it is possibe to control input gain via e.g. Windows.

![InputGain](https://user-images.githubusercontent.com/20726856/106431543-b7098780-646d-11eb-9372-16c2555f86b0.png)

I get your point: Inexperienced users probably don't know about this setting.

How this can be done should be documented in the Jamulus documentation and surely some kind of help should be in Jamulus. Any ideas?

The [guideline](https://github.com/jamulussoftware/jamulus/discussions/915) suggests the "Keep it simple and stupid" approach. In my case, minimalism made it possible to onboard inexperienced users who were/might have been overwhelmed or intimidated with features from other more full-featured applications. Not that I say your feature request might result in Jamulus becoming intimidating or overwhelming people, but at least for me Jamulus was the only application who was simple enough to be understood by inexperienced users (= choir members) due to the KISS approach. That's why I support it too and might be a bit conservative ;-).

A change like this might require a lot of code changes and - once too many duplicate features are implemented - result in a cluttered UI and therefore a worse UX. Exactly the opposite to what you wanted to solve with this problem. That's why - in my opinion - we should try to solve the problem differently. I think there even was a discussion before about this issue here. Adding a slider like this might not even be possible due to some technical reasons I don't exactly remember.

Any further ideas?

**Comment by jugo6** [comment]
On keeping it simple: I think windows is keeping it far from simple by having to execute at least 6 steps to reach the control, and than you still have to find the right microphone/audio in to select, which is also not error-proof I found.  I made several Help documents to tackle this. I found that for some people each week their volume is different, set by other programs accessing the volume settings....

Duplicate feature: in my current setup I sometimes have 4 or more points to control my volume. I don't see that as a problem. In a normal mixer situation you set you gain up to just below clipping at mix signal, and you still have a volume slider. (However one can argue about that being the mix so the right side of Jamulus.)

Tony suggested in facebook Jamulus Official a problem might be that the sound input is different in each OS. I hope at some stage we can still "grab " the signal before going out :-)

thanks for thinking along !

**Comment by 38github** [comment]
Yes, an input drive would be a great feature. I know that some people use condensor microphones that even at lowest gain on the interface is louder than the rest of the musicians. I think the user should in first hand be able to set a reasonable loudness (-23 LUFS or whatever fits others or server rules) than the others having to lower every participant with to louud volume. This is one of many features that I think Jamulus need now to it is popular and the servers are crowded with people who do not know how to setup their sound and make it hard for others to enjoy the stay in channels.

**Comment by gilgongo** [comment]
Hi All, this doesn't look like something that will be solved any time soon for a number of difficult technical reasons.

We'd also like to clear up the Issues so that it only has defined actions for the backlog. So I'm moving this to a discussion. If and when an implementable and agreed solution is found, we can raise that as a ticket an reference this discussion if need be. 

![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-e453f381-f13d-466a-a20e-c03c786b333b-v1.png?transparent=1&palette=1&width=246)
